Name: seckill-service
Mode: dev
ListenOn: 0.0.0.0:8090
Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: seckill.rpc

Database:
  Host: 127.0.0.1
  Port: 3306
  User: root
  Password: "123456"
  Database: ecommerce
  Charset: utf8mb4
  MaxOpenConns: 100
  MaxIdleConns: 10
  ConnMaxLifetime: 3600
  ConnMaxIdleTime: 600

BizRedis:
  Host: 127.0.0.1
  Port: 6379
  Password: ""
  Database: 0
  PoolSize: 10
  MinIdleConns: 5

Kafka:
  Brokers:
    - 127.0.0.1:9092
  Version: 2.8.0
